# Generated by Django 3.2.23 on 2023-12-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231216_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
